const translations = {
    en: {
        Home: "Home",
        Experience: "Experience",
        Gallery: "Gallery",
        Certificate: "Certificate",
        Contact: "Contact",
        welcome: "Welcome to my website. Here, you will find my resume alongside my experiences in management and administrative training.",
        About: "About Me",
        // AP: "Marital Status: Single. Military Service: completed.Date of Birth: January 27th, 1998. Nationality: Egyptian.",
        AP: "Marital Status: Single.",
        AP_2: " Military Service: completed.",
        AP_3: "Date of Birth: January 27th, 1998.",    
        AP_4: " Nationality: Egyptian.",
        Skills: "Skills",
        Objective: "Objective",
        Educatio: "Education",
        Computer: "Computer Skills :-",
        proficient: "● proficient user of Windows 11, Microsoft Office (Word, Excel, PowerPoint and outlook).",
        Language: "Language Skills :-",
        Arabic: "● Arabic: Mother tongue.",
        Good: "● Good command of English.",
        Objectives: "Objectives :-",
        Seeking: "Seeking a challenging and competitive job opportunity in the teaching field which I can combine all knowledge, experience and abilities.",
        Bachelor: "I'am a Bachelor of Commerce, Business Administration major graduate looking to work in a global and highly reputable company, which will benefit from my comprehensive knowledge through my study in Business Administration.",
        educations: "Education  :-",
        Business: "● Bachelor of Business Administration, Faculty of Commerce, Mansoura University, May 2020.",
        Grade: "Grade:",
        Very: "● Very Good.",
        My: "My Experience",
        Umm: "Umm Al-Qura Institutes for Training (Branch Supervisor) ",
        day: "●Supervising the day-to-day operations of the administrative department and staff members.",
        employees: "●training, and evaluating employees and taking corrective action when necessary.",
        Umm_1:"● Ensuring necessary supplies and that all equipment is working and properly maintained.",
        Umm_2:"● Plan, implement and oversee the work of staff members to ensure efficiency and compliance with organizational requirements and company procedures. Collecting, organizing, and storing information using computers and filing systems.",
        Umm_3:"● Collect, organize, and store information using computers and filing systems.",
        Umm_4:"● tracking progress towards company goals.",
        Umm_5:"● Preparing reports for the branch.",
        Umm_6:"● Distribution of tasks.",
        Al:"Umm Al-Qura Institutes for Training (Business career coach) ",
        lectures:"●Delivering lectures and presentations on various topics related to commerce and vocational skills.",
        Developing:"●Developing curricula and educational materials to meet the needs of trainees.",
        career_coach_3:"● Assessing trainees' performance and providing feedback to enhance their skills.",
        career_coach_4:"● Organizing workshops and practical activities to reinforce applied understanding.",
        career_coach_5:"● Preparing periodic evaluation reports on trainees' progress and presenting them to management.",
        career_coach_6:"● Guiding and mentoring trainees in their career paths and helping them set professional goals.",
        career_coach_7:"● organizing individual and group training sessions.",
        career_coach_8:"● Providing technical and informational support to trainees on various commercial topics.",
        career_coach_9:"● Delivered interactive and engaging lectures to enhance critical thinking and problem-solving skills.",
        career_coach_10:"● Assisted in creating, organizing, and implementing curricula for a variety of courses.",
        career_coach_11:"● Participated in professional development activities to stay updated on best practices and trends in education.",
        more:"Learn more",
        Vivo:"Vivo smart phone (trainer)",
        trainer_1:"● Plan, implement and oversee the work of staff members to ensure efficiency and compliance with organizational requirements and company procedures.",
        trainer_2:"● Conduct ongoing safety audits, meet with individual staff members, attend company safety meetings and participate or direct other work activities designed to promote work safety and encourage continuing education among staff members.";
        trainer_3:"● evaluating the knowledge and skills and the ability of the employees.",
        trainer_4:"● organizing appropriate training for all staff members.",
        trainer_5:"● responsible for train the new employees.",
        mnmn:"See More",
        Galler:"Gallery",
        CV:"Download CV",
        sub:"Submit",
        Certifi:"Certificate",
        me:"My Experience",
        hyper: "Hyper Elmataria, Assistant purchasing manager (Assistant purchasing manager) ",
        hyper_1:"● Assisting with the inspection of goods.",
        hyper_2:"● provides administrative support to a purchasing manager. By assessing the needs of the company or organization.",
        hyper_3:"● assist the manager in making choices about supplier sourcing, procurement, and vendor negotiations.",
        hyper_4:"● help determine pricing strategies that allow the company to remain competitive and profitable.",
        hyper_5:"● work with other procurement analysts to make forecasts about future demand.",
       
    },
    ar: {
        Home: "الرئيسيه",
        Experience: "خبره",
        Gallery: "معرض الصور",
        Certificate: "الشهادات",
        Contact: "تواصل معي",
        welcome: " مرحباً بكم في موقعي الإلكتروني. هنا ستجدو سيرتي الذاتية إلى جانب خبراتي في مجال الإدارة والتدريب الإدارى ",
        About: "المعلومات الشخصية",
        // AP: "الحالة الاجتماعية: أعزب. الخدمة العسكرية: انتهت. تاريخ الميلاد: 27 يناير 1998. الجنسية: مصرية.",
        AP: "الحالة الاجتماعية: أعزب .",
        AP_2: "الخدمة العسكرية: تم الانتهاء." ,
        AP_3: " تاريخ الميلاد: 27 يناير 1998 .",    
        AP_4: " الجنسية: مصرية.",
        Skills: "مهاراتي",
        Objective: "أهدافي",
        Educatio: "التعليم",
        Computer: "مهارات الحاسوب :-",
        proficient: "● مستخدم ماهر لنظام التشغيل Windows 11، وMicrosoft Office (Word، Excel، PowerPoint و outlook).",
        Language: "مهارات اللغه :-",
        Arabic: "● العربية: اللغة الأم.",
        Good: "●إتقان اللغة الإنجليزية.",
        Objectives: "أهدافي :-",
        Seeking: "أبحث عن العمل في شركة عالمية وذات سمعة عالية، والتي ستستفيد من معرفتي الشاملة التي اكتسبتها من خلال دراستي في إدارة الأعمال وخبراتي السابقة .",
        Bachelor: "أسعي ايضا للحصول على فرصة عمل تنافسية وتحديّة في مجال التدريس، أتمكن من خلالها من دمج كل ما لدي من معرفة وخبرة وقدرات .",
        education: "التعليم :-",
        Business: "● بكالوريوس إدارة الأعمال كلية التجارة جامعة المنصورة مايو 2020م.",
        Grade: "التقدير :",
        Very: "● جيد جدا.",
        My: "خبرة العمل",
        Umm: " معاهد أم القرى للتدريب (مشرف فرع) ",
        day: "●الإشراف على العمليات اليومية للقسم الإداري وأعضاء الفريق .",
        employees: "● تدريب الموظفين وتقييمهم واتخاذ الإجراءات التصحيحية عند الضرورة.",
        Umm_1:"● ضمان توافر الإمدادات اللازمة وأن جميع المعدات تعمل ويتم صيانتها بشكل جيد. ",
        Umm_2:"● تخطيط وتنفيذ والإشراف على عمل أعضاء الفريق لضمان الكفاءة والامتثال لمتطلبات المنظمة وإجراءات الشركة. ",
        Umm_3:"● جمع وتنظيم وتخزين المعلومات باستخدام الحاسوب وأنظمة الأرشفة. ",
        Umm_4:"● متابعة التقدم نحو تحقيق أهداف الشركة. ",
        Umm_5:"● إعداد التقارير للفرع. ",
        Umm_6:"● توزيع المهام.",
        Al: "  معاهد أم القرى للتدريب (مدرب مهني) ",
        lectures:"● إلقاء محاضرات وعروض تقديمية حول مواضيع مختلفة تتعلق بالتجارة والمهارات المهنية.",
        Developing:"● تطوير المناهج والمواد التعليمية بما يتناسب مع احتياجات المتدربين.",
        career_coach_3:"● تقييم أداء المتدربين وتقديم ملاحظات لتعزيز مهاراتهم.",
        career_coach_4:"● تنظيم ورش العمل والأنشطة العملية لتعزيز الفهم التطبيقي",
        career_coach_5:"● التعاون مع فرق متعددة التخصصات لتحسين جودة البرامج التدريبية.",
        career_coach_6:"● إعداد تقارير تقييم دورية عن تقدم المتدربين وتقديمها للإدارة.",
        career_coach_7:"● تنظيم جلسات تدريب فردية وجماعية. ",
        career_coach_8:"● توجيه وإرشاد المتدربين في مساراتهم المهنية ومساعدتهم في تحديد أهدافهم المهنية.",
        career_coach_9:"● تقديم الدعم الفني والمعلوماتي للمتدربين حول مواضيع تجارية متنوعة.",
        career_coach_10:"● ألقى محاضرات تفاعلية وجذابة لتعزيز التفكير النقدي ومهارات حل المشكلات.",
        career_coach_11:"● ساعد في إنشاء وتنظيم وتنفيذ المناهج لمجموعة متنوعة من الدورات.",
        more:"المزيد",
        Vivo:"شركة فيفو للهواتف الذكية (مدرب مهارات البيع و التوظيف)",
        trainer_1:"● تخطيط وتنفيذ والإشراف على عمل أعضاء الفريق لضمان الكفاءة والامتثال لمتطلبات المنظمة وإجراءات الشركة.",
        trainer_2:"● إجراء تدقيقات أمان مستمرة، الاجتماع مع الأفراد من أعضاء الفريق، حضور اجتماعات الأمان الخاصة بالشركة، والمشاركة أو توجيه الأنشطة الأخرى المصممة لتعزيز السلامة في العمل وتشجيع التعليم المستمر بين الأعضاء. ";
        trainer_3:"● تقييم المعرفة والمهارات وقدرة الموظفين. ",
        trainer_4:"● تنظيم التدريب المناسب لجميع أعضاء الفريق. ",
        trainer_5:"● المسؤولية عن تدريب الموظفين الجدد.",
        mnmn:"المزيد",
        Galler:"الصور",
        CV:"تحميل السيره الذاتيه",
        sub:"ارسال",
        Certifi:"الدورات التدريبية",
        me:"خبراتي",
        hyper: "هايبر المطرية (مساعد مدير المشتريات) ",
        hyper_1:"● المساعدة في فحص السلع.",
        hyper_2:"● تقديم الدعم الإداري لمدير المشتريات من خلال تقييم احتياجات الشركة أو المنظمة.",
        hyper_3:"● مساعدة المدير في اتخاذ القرارات المتعلقة بمصادر الموردين، والشراء، والتفاوض مع الموردين.",
        hyper_4:"● المساعدة في تحديد استراتيجيات التسعير التي تتيح للشركة أن تظل تنافسية ومربحة.",
        hyper_5:"● العمل مع محللي المشتريات الآخرين لإجراء توقعات حول الطلب المستقبلي.",
            }
};

function setLanguage(lang) {
    document.querySelectorAll("[data-key]").forEach(element => {
        const key = element.getAttribute("data-key");
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
}

document.getElementById("lang-switcher").addEventListener("click", () => {
    const currentLang = document.documentElement.lang === "ar" ? "en" : "ar";
    document.documentElement.lang = currentLang;
    setLanguage(currentLang);
    document.getElementById("lang-switcher").textContent = currentLang === "ar" ? "EN" : "AR";
});

setLanguage(document.documentElement.lang);